# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings - PRD aligned
title: Calen Irwin
email: calen.irwin@gmail.com
tagline: building ai and building with ai
description: >-
  Data scientist specializing in rail autonomy at Hitachi Rail in Toronto.
  Passionate about learning, sharing knowledge, and exploring the intersection
  of technology and transportation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://calenirwin.github.io" # the base hostname & protocol for your site
twitter_username: calenirwin
github_username: calenirwin
linkedin_username: calen-b-irwin

# Author information
author:
  name: Calen Irwin
  email: calen.irwin@gmail.com
  bio: "Data scientist specializing in autonomy at Hitachi Rail"
  location: "Toronto, Ontario"
  company: "Hitachi Rail"
  role: "Data Scientist - Rail Autonomy"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Kramdown settings for MathJax
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num/"

# SEO
seo:
  type: Person
  name: Calen Irwin
  description: Data scientist specializing in rail autonomy at Hitachi Rail in Toronto
  url: https://calenirwin.github.io
  image: /assets/images/calen-headshot-2022.jpeg
  twitter:
    username: calenirwin
  social:
    name: Calen Irwin
    links:
      - https://github.com/calenirwin
      - https://linkedin.com/in/calen-b-irwin
      - mailto:calen.irwin@gmail.com

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
